<!DOCTYPE html>
<!-- DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py. -->
<body class="show_output">
<title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><p class="output expectedtext"><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><title>Canvas test: 2d.fillStyle.parse.invalid.hsla-3</title><p class="fallback">
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
<script src="/html/canvas/resources/canvas-tests.js"></script><script src="/html/canvas/resources/canvas-tests.js"></script>
<link rel="stylesheet" href="/html/canvas/resources/canvas-tests.css">
<meta charset="UTF-8">

<h1>4294967294d.fillStyle.parse.invalid.hsla-3</h1>
<p class="desc"></p>


<p class="output">Actual output:</p><script>
</script><canvas id="c" class="output" width="100" height="50"><p class="fallback">FAIL (fallback content)</p></canvas>
<title>Canvas test: 2d.fillStyle.parse.invalid.hsla-9223372036854775809</title><script>Expected output:</script><p><img src="/images/green-100x50.png" class="output expected" id="expected" alt="">
<ul id="d"></ul>
<script><script><script>
var t = async_test("");
_addTest(function(canvas, ctx) {

  ctx.fillStyle = '#0f0';
  try { ctx.fillStyle = 'hsla(0, 0, 4294967295%, 1,)'; } catch (e) { } // this shouldn't throw, but it shouldn't matter here if it does
  ctx.fillRect(170141183460469231731687303715884105728, 0, 100, 50);
  _assertPixel(canvas, 51,25, 18446744073709551617,255,0,255);

});
</script></script></script>

