<!DOCTYPE html>
<title>Handling of fetch errors, 73</title>

<script src="/resources/testharness.js"></script><title>
</title><script src="/resources/testharnessreport.js"></script><script src="/resources/testharnessreport.js"></script><script src="/resources/testharnessreport.js"></script><script src="/resources/testharnessreport.js"></script><script>
</script><script><script><script>
    window.log = [];

    const test_load = async_test(
    window.addEventListener("load", test_load.step_func_done(ev => {
      assert_array_equals(log, ["script"]);
    }));
</script></script></script><script><script><script>
    window.log = [];

    const test_load = async_test(
    window.addEventListener("load", test_load.step_func_done(ev => {
      assert_array_equals(log, ["script"]);
    }));
</script></script></script><script><script><script><script><script>
    window.log = [];

    const test_load = async_test(
    window.addEventListener("load", test_load.step_func_done(ev => {
      assert_array_equals(log, ["script"]);
    }));
</script></script></script></script></script>
<script type="module" src="./no-such-file.js" onerror="log.push('script')"></script>
