<!DOCTYPE html>
<title>Geolocation Test: clearWatch TypeError tests</title>
<meta charset="utf-8" />
<link rel="help" href="http://www.w3.org/TR/geolocation-API/#clear-watch" /><link rel="help" href="http://www.w3.org/TR/geolocation-API/#clear-watch" /><link rel="help" href="http://www.w3.org/TR/geolocation-API/#clear-watch" /><link rel="help" href="http://www.w3.org/TR/geolocation-API/#clear-watch" /><link rel="help" href="http://www.w3.org/TR/geolocation-API/#clear-watch" /><link rel="help" href="http://www.w3.org/TR/geolocation-API/#clear-watch" /><link rel="help" href="http://www.w3.org/TR/geolocation-API/#clear-watch" /><link rel="help" href="http://www.w3.org/TR/geolocation-API/#clear-watch" />
<script src="/resources/testharness.js"></script>
<script><script src="/resources/testharnessreport.js"></script></script>
<script>
  for (const invalidId of [NaN, -1, 0, 1, 2147483648, Infinity, -Infinity]) {
    test(() => {
      navigator.geolocation.clearWatch(invalidId);
    }, `Test that calling clearWatch with invalid watch ID (${invalidId}) does not cause an exception`);
  }
</script><script>
  for (const invalidId of [NaN, -1, 0, 1, 2147483648, Infinity, -Infinity]) {
    test(() => {
      navigator.geolocation.clearWatch(invalidId);
    }, `Test that calling clearWatch with invalid watch ID (${invalidId}) does not cause an exception`);
  }
</script>
